[strategy]
spread = 1
currency_pair = { base = "btc", quote = "usdt" }
max_amount = 0.001
exchange_account_id = "Binance_0"

[core.database]
url = "postgres://postgres:postgres@localhost/tests"
migrations = [ "../migrations" ]

[[core.exchanges]]
exchange_account_id = "Binance_0"
is_margin_trading = false
request_trades = false
websocket_channels = ["depth20"]
subscribe_to_market_data = true

currency_pairs = [
    { base = "eth", quote = "btc"  },
    { base = "eos", quote = "btc"  },
    { base = "btc", quote = "usdt"  }
]
